In [1]:
import pandas as pd
import openpyxl
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

In [2]:
raw=pd.read_excel("/workspaces/Customer_Segmentation_KMeans_Clustering/data/raw/Online Retail.xlsx")
raw.head(2)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [3]:
print('shape before wrangling:', raw.shape)

shape before wrangling: (541909, 8)

In [4]:
from src.data.cleaner import DataCleaner
cleaner=DataCleaner(raw)
df=cleaner.wrangle()
print('shape after wrangling:', df.shape)

shape after wrangling: (4239, 7)

In [5]:
print('Raw shape after running cleaner:', raw.shape)

Raw shape after running cleaner: (541909, 8)

In [7]:
from src.data.loader import DataLoader
path="/workspaces/Customer_Segmentation_KMeans_Clustering/data/raw/Online Retail.xlsx"
loader=DataLoader(path)
df=loader.load_data()
df.shape

(541909, 8)

In [8]:
df.head(2)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [18]:
from src.data.validator import DataValidator
validator=DataValidator(df)
validator.validate_columns()

'columns match as expected'